# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addInMatrix <- function(vec, M) {
    .Call('_treeSeg_addInMatrix', PACKAGE = 'treeSeg', vec, M)
}

allComb <- function(lengths) {
    .Call('_treeSeg_allComb', PACKAGE = 'treeSeg', lengths)
}

ancestor <- function(node, tree) {
    .Call('_treeSeg_ancestor', PACKAGE = 'treeSeg', node, tree)
}

boundsCall <- function(x, alpha, q, fam) {
    .Call('_treeSeg_boundsCall', PACKAGE = 'treeSeg', x, alpha, q, fam)
}

bouPos <- function(ny, li, ri) {
    .Call('_treeSeg_bouPos', PACKAGE = 'treeSeg', ny, li, ri)
}

colSums <- function(X) {
    .Call('_treeSeg_colSums', PACKAGE = 'treeSeg', X)
}

getNewCandidates <- function(subroot, aN, tree, minIVar, isOffMat, without) {
    .Call('_treeSeg_getNewCandidates', PACKAGE = 'treeSeg', subroot, aN, tree, minIVar, isOffMat, without)
}

#' Offspring tips of given inner node
#' 
#' Gives back all tips of a \code{tree} which are an offspring of 
#' a given \code{node} of the tree
#' @param node single integer value which contrains the index of a node from \code{tree}
#' @param tree rooted tree object
#' @return Integer vector with all indeces of offspring tips of \code{node} in \code{tree}.
#' @examples 
#' library(ape)
#' n <- 2 * 50
#' tree <- rtree(n, rooted = TRUE)
#' aktiveNode <- n + 50
#' offAktiveNode <- getOffspringTip(aktiveNode,tree)
#' @export
getOffspringTip <- function(node, tree) {
    .Call('_treeSeg_getOffspringTip', PACKAGE = 'treeSeg', node, tree)
}

getOffspringTipB <- function(node, tree) {
    .Call('_treeSeg_getOffspringTipB', PACKAGE = 'treeSeg', node, tree)
}

mlCost <- function(y, fam) {
    .Call('_treeSeg_mlCost', PACKAGE = 'treeSeg', y, fam)
}

mycombn <- function(n, k) {
    .Call('_treeSeg_mycombn', PACKAGE = 'treeSeg', n, k)
}

offspring <- function(node, tree) {
    .Call('_treeSeg_offspring', PACKAGE = 'treeSeg', node, tree)
}

#' All offspring nodes of given inner node
#' 
#' Gives back all nodes of a \code{tree} which are an offspring of 
#' a given \code{node} of the tree
#' @param node single integer value which contrains the index of a node from \code{tree}
#' @param tree rooted tree object
#' @return Integer vector with all indeces of offspring nodes of \code{node} in \code{tree}.
#' @examples 
#' library(ape)
#' n <- 2 * 50
#' tree <- rtree(n, rooted = TRUE)
#' aktiveNode <- n + 50
#' offAktiveNode <- offspringAll(aktiveNode,tree)
#' @export
offspringAll <- function(node, tree) {
    .Call('_treeSeg_offspringAll', PACKAGE = 'treeSeg', node, tree)
}

offspringDiff <- function(Node, node, tree) {
    .Call('_treeSeg_offspringDiff', PACKAGE = 'treeSeg', Node, node, tree)
}

offspringDiffTip <- function(Node, node, tree) {
    .Call('_treeSeg_offspringDiffTip', PACKAGE = 'treeSeg', Node, node, tree)
}

#' @useDynLib treeSeg
#' @importFrom Rcpp evalCpp
NULL

prepTree <- function(tree) {
    .Call('_treeSeg_prepTree', PACKAGE = 'treeSeg', tree)
}

segTree <- function(y, tree, q = NA_real_, alpha = 0.05, fam = 0L) {
    .Call('_treeSeg_segTree', PACKAGE = 'treeSeg', y, tree, q, alpha, fam)
}

sortComb <- function(ncomb, cost) {
    .Call('_treeSeg_sortComb', PACKAGE = 'treeSeg', ncomb, cost)
}

subsetSum <- function(numbers, target, maxSize) {
    .Call('_treeSeg_subsetSum', PACKAGE = 'treeSeg', numbers, target, maxSize)
}

vecmin <- function(x) {
    .Call('_treeSeg_vecmin', PACKAGE = 'treeSeg', x)
}

vecmax <- function(x) {
    .Call('_treeSeg_vecmax', PACKAGE = 'treeSeg', x)
}

